### ISSUE TITLE
Problem with gulp-sourcemaps and gulp-autoprefixer

### ISSUE THREAD

**Issue by evgeniy-vashchuk** [gulp-sourcemaps/gulp-sourcemaps#355] opened 2018-10-06 20:04 UTC
I have a problem with generated sourcemaps, if I have gulp-autoprefixer in in the stream of my styles task. Source maps file is generated, but in browser they show absolutely wrong files. But if I remove gulp-autoprefixer from stream, sourcemaps are shown correctly. I know about [Plugins with gulp sourcemaps support](https://github.com/gulp-sourcemaps/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support)

![3cc78d8df7](https://user-images.githubusercontent.com/24987866/46575254-d174e880-c9ba-11e8-8b80-762191b7794d.png)

I try to insert autoprefixer by gulp-postcss, but in this way I have the same situation (wrong files in browser)

What I must to do, to be able to compile SASS with correct sourcemaps and with autoprefixer?

Code with gulp-autoprefixer:

```
// WORKING WITH SASS FILES
gulp.task('sass', function() {
	return gulp.src('dev/scss/all.scss')
	.pipe(sourcemaps.init())
	.pipe(sass({
		//outputStyle: 'compressed', // minify css (optional)
		indentType: 'tab',
		indentWidth: 1
	}).on("error", notify.onError({
		title: "Error compiling SASS"
	})))
	.pipe(autoprefixer(['last 3 versions']))
	.pipe(sourcemaps.write('.'))
	.pipe(gulp.dest('dev/css'))
	.pipe(browserSync.reload({stream: true}))
});
```

Code with postcss and autoprefixer:

```
// WORKING WITH SASS FILES
gulp.task('sass', function() {
	return gulp.src('dev/scss/all.scss')
	.pipe(sourcemaps.init())
	.pipe(sass({
		//outputStyle: 'compressed', // minify css (optional)
		indentType: 'tab',
		indentWidth: 1
	}).on("error", notify.onError({
		title: "Error compiling SASS"
	})))
	.pipe(postcss([ autoprefixer(['last 3 versions']) ]))
	.pipe(sourcemaps.write('.'))
	.pipe(gulp.dest('dev/css'))
	.pipe(browserSync.reload({stream: true}))
});
```

**Comment by retan** [comment] 2018-10-15 08:44
Same problem here!

**Comment by nmccready** [comment] 2018-10-15 13:49
Dupe of #349

**Closed by nmccready** 2018-10-15 13:49 UTC
