### ISSUE TITLE
npm i gulp-sourcemaps gives 404 for npm > 2.7.0

### ISSUE THREAD

**Issue by pgangwani** [gulp-sourcemaps/gulp-sourcemaps#308] opened 2017-05-05 13:35 UTC
As per new feature of scoped-packages in npm version 2.7.0 (https://docs.npmjs.com/getting-started/scoped-packages) , 
 @gulp-sourcemaps/identity-map will be taken as @username/project-name

that's the reason it throws 404, 

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 User not found : @gulp-sourcemaps/identity-map
npm ERR! 404 
npm ERR! 404  '@gulp-sourcemaps/identity-map' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pgang1/.npm/_logs/2017-05-05T13_30_26_752Z-debug.log

Shall we fix this blocker issue?

**Comment by phated** [comment] 2017-05-05 15:21
This is by design. Closing as duplicate.

**Closed by phated** 2017-05-05 15:21 UTC

**Comment by pgangwani** [comment] 2017-05-12 21:25
@phated : What should I do to resolve this issue in my machine ?
