### ISSUE TITLE
'gulp-sourcemaps/map-sources' is not in the npm registry.

### ISSUE THREAD

**Issue by lasotaartur** [gulp-sourcemaps/gulp-sourcemaps#293] opened 2017-03-29 08:10 UTC
Today I have problem like below:
```
 error 404 Not Found
4121 error 404
4121 error 404 'gulp-sourcemaps/map-sources' is not in the npm registry.
4121 error 404 You should bug the author to publish it
4121 error 404 It was specified as a dependency of 'gulp-sourcemaps'
```
Yesterday it worked

**Comment by boxcee** [comment] 2017-03-29 08:45
Duplicate of [Issue 292](https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/292)

**Comment by qrpike** [comment] 2017-03-29 12:06
Getting same issue

**Comment by nmccready** [comment] 2017-03-29 14:32
Closing due to dupe; please if your having proxy problems roll back your version. Use stricter versioning, npm shrinkwrap or yarn.lock .

**Closed by nmccready** 2017-03-29 14:32 UTC

**Comment by phated** [comment] 2017-03-29 15:38
Or a better proxy ;)

**Comment by phated** [comment] 2017-03-29 21:56
If you are using `sinopia`, you probably want to switch to https://github.com/verdaccio/verdaccio
