### ISSUE TITLE
not existing sources in sourcemap

### ISSUE THREAD

**Issue by philerck** [gulp-sourcemaps/gulp-sourcemaps#350] opened 2018-04-20 10:33 UTC
I have this gulp task:

gulp.task('css', function() {
  return gulp
    .src('src/assets/css/*.scss')
    .pipe(plugins.plumber({ errorHandler: onError }))
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.sass())
    .pipe(plugins.postcss([plugins.postcssCssnext()]))
    .pipe(plugins.cleanCss())
    .pipe(plugins.rename({ suffix: '.min' }))
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(gulp.dest('build/assets/css'))
    .pipe(bs.stream())
    .pipe(plugins.notify({ title: 'CSS changed' }));
});

and in my generated sourcemap I have in sources: style.css and no-source. How can I get rid of them.
All my scss files are also in the sourcemap.

**Comment by nmccready** [comment] 2018-06-28 17:58
Dupe of #349

**Closed by nmccready** 2018-06-28 17:58 UTC
